// This script collects all sections (logic questions for sections 1 to 9) into one MongoDB database.
const mongoose = require('mongoose');
// Connecting to the English version of the database
mongoose.connect('mongodb://127.0.0.1:27017/ai_quiz_db')
    .then(() => console.log("✅ Connection successfully established!"))
    .catch(err => console.error("❌ Connection error:", err));
// Defining the schema model for tests
const Quiz = mongoose.model('Quiz', new mongoose.Schema({ section: String, questions: Array }));

const data = [
    {
		section: "Section 1: AI BASICS AND HISTORY",
		questions: [
			{ id: 1, question: "What is Artificial Intelligence (AI)?", options: ["A simple program", "Simulation of human intelligence", "A game", "A robot"], correct_answer: "Simulation of human intelligence", explanation: "AI is a technology that allows a computer to think, learn, and make decisions independently, similar to a human." },
			{ id: 2, question: "In what year did the term AI first appear?", options: ["1950", "1956", "1960", "1945"], correct_answer: "1956", explanation: "The term 'Artificial Intelligence' was first proposed by John McCarthy at the Dartmouth Conference in 1956." },
			{ id: 3, question: "Who is called the father of AI?", options: ["Alan Turing", "John McCarthy", "Elon Musk", "Steve Jobs"], correct_answer: "John McCarthy", explanation: "John McCarthy was the founder of the AI field and the creator of the LISP programming language." },
			{ id: 4, question: "What is the Turing Test for?", options: ["Computer speed", "Thinking ability", "Memory", "Screen quality"], correct_answer: "Thinking ability", explanation: "This test determines if a computer can behave in a way that is indistinguishable from a human." },
			{ id: 5, question: "What is a Turing Machine?", options: ["Theoretical computer model", "A real car", "A phone", "A microchip"], correct_answer: "Theoretical computer model", explanation: "It is a mathematical model of computation that formed the basis for all modern computers." },
			{ id: 6, question: "What is Strong AI?", options: ["AI with human consciousness", "High-speed AI", "A large robot", "A banking system"], correct_answer: "AI with human consciousness", explanation: "Strong AI is a hypothetical type of AI that possesses consciousness and the ability to solve any intellectual task a human can." },
			{ id: 7, question: "Whom did the Deep Blue computer defeat?", options: ["Kasparov", "Magnus", "Karpov", "Fischer"], correct_answer: "Kasparov", explanation: "In 1997, the Deep Blue supercomputer defeated world champion Garry Kasparov in a chess match for the first time." },
			{ id: 8, question: "What is Machine Learning?", options: ["Learning based on experience", "Writing code", "Assembling parts", "Computer repair"], correct_answer: "Learning based on experience", explanation: "This is a subfield of AI that allows algorithms to learn from data without direct programming." },
			{ id: 9, question: "Which programming language was the first for AI?", options: ["LISP", "Python", "Java", "C++"], correct_answer: "LISP", explanation: "The LISP language was created in 1958 by John McCarthy specifically for artificial intelligence research." },
			{ id: 10, question: "What is the significance of Big Data for AI?", options: ["Fuel for training", "It does not matter", "Only for storage", "Turning off AI"], correct_answer: "Fuel for training", explanation: "Training complex AI models requires a massive amount of data (Big Data)." },
			{ id: 11, question: "What was the first industrial robot called?", options: ["Unimate", "Sophia", "Tesla Bot", "Asimo"], correct_answer: "Unimate", explanation: "Unimate was the first industrial robot to start working at a General Motors plant in 1961." },
			{ id: 12, question: "What is Weak AI?", options: ["For a single task", "Stupid", "Slow", "Universal"], correct_answer: "For a single task", explanation: "Weak AI is designed to perform only one specific task (e.g., facial recognition)." },
			{ id: 13, question: "What does cybernetics study?", options: ["Control and communication", "History", "Plants", "Earth"], correct_answer: "Control and communication", explanation: "Cybernetics is the science of general patterns of control and information transmission in machines and organisms." },
			{ id: 14, question: "What does the abbreviation GPT stand for?", options: ["Generative Pre-trained Transformer", "General Power", "Global Point", "Get Point"], correct_answer: "Generative Pre-trained Transformer", explanation: "This is a neural network architecture used to generate human-like text." },
			{ id: 15, question: "Into how many main groups is artificial intelligence divided?", options: ["2 groups", "10 groups", "5 groups", "3 groups"], correct_answer: "2 groups", explanation: "AI is typically divided into two main groups: Narrow/Weak AI and General/Strong AI." }
		]
	},
    {
		section: "Section 2: HUMAN BRAIN AND AI",
		questions: [
			{ id: 16, question: "What do artificial neurons imitate?", options: ["The brain", "Stars", "Electricity", "Water"], correct_answer: "The brain", explanation: "Neural networks are built based on the biological structure of nerve cells (neurons) in the human brain." },
			{ id: 17, question: "What is a synapse in a neural network?", options: ["Connection weight", "Memory", "A screen", "A button"], correct_answer: "Connection weight", explanation: "A synapse is the connection point between two neurons, which in AI serves as the weight for transmitting a signal." },
			{ id: 18, question: "Deep Learning is a subfield of what?", options: ["Machine Learning", "Hardware", "Internet", "Design"], correct_answer: "Machine Learning", explanation: "Deep Learning is a type of machine learning that utilizes multi-layered neural networks." },
			{ id: 19, question: "Where are the hidden layers located in AI?", options: ["Between input and output", "Inside the monitor", "In the keyboard", "On the Internet"], correct_answer: "Between input and output", explanation: "Neural networks consist of input, hidden, and output layers; calculations are performed specifically within the hidden layers." },
			{ id: 20, question: "What is Supervised Learning?", options: ["Learning on labeled data", "Without control", "By itself", "With text only"], correct_answer: "Learning on labeled data", explanation: "In this method, the algorithm is provided with examples along with the correct answers for training." },
			{ id: 21, question: "What is Unsupervised Learning?", options: ["Learning without correct answers", "With control", "From a book", "With a teacher"], correct_answer: "Learning without correct answers", explanation: "The algorithm independently identifies patterns and groups (clusters) within the data." },
			{ id: 22, question: "What is Backpropagation used for?", options: ["To correct errors", "For printing", "To turn off", "For speed"], correct_answer: "To correct errors", explanation: "This algorithm passes the error from the end of the network back to the beginning, adjusting neuron weights to improve the result." },
			{ id: 23, question: "How many main parts does a biological neuron consist of?", options: ["3 parts", "10 parts", "1 part", "5 parts"], correct_answer: "3 parts", explanation: "A biological neuron consists of dendrites (input), the cell body, and an axon (output)." },
			{ id: 24, question: "Who is a Data Scientist?", options: ["Data specialist", "A doctor", "A driver", "A chef"], correct_answer: "Data specialist", explanation: "This is a person who analyzes big data and uses it to create AI models." },
			{ id: 25, question: "Who created the 'Perceptron' algorithm?", options: ["Frank Rosenblatt", "Elon Musk", "Bill Gates", "Mark Zuckerberg"], correct_answer: "Frank Rosenblatt", explanation: "In 1957, Frank Rosenblatt created the perceptron—the simplest model of a neural network." },
			{ id: 26, question: "How many neurons are in the human brain?", options: ["About 86 billion", "1 million", "100 thousand", "5 billion"], correct_answer: "About 86 billion", explanation: "The human brain contains an incredibly complex network of neurons that AI attempts to imitate." },
			{ id: 27, question: "What is an Activation Function in AI?", options: ["A decision to pass a signal", "Powering off", "Saving a file", "Showing a picture"], correct_answer: "A decision to pass a signal", explanation: "This function determines whether a neuron should be activated and pass the signal to the next layer or not." },
			{ id: 28, question: "What is Reinforcement Learning?", options: ["Learning through rewards and penalties", "Reading a book", "Watching a video", "Using numbers only"], correct_answer: "Learning through rewards and penalties", explanation: "The algorithm acts in an environment, receiving a reward for a good result and a penalty for a mistake." },
			{ id: 29, question: "Can AI feel like a human?", options: ["No (at least for now)", "Yes", "Laughter only", "Fear only"], correct_answer: "No (at least for now)", explanation: "AI processes only mathematics and data; it has no real capacity for emotional feelings." },
			{ id: 30, question: "What is neuroplasticity?", options: ["The brain's ability to change", "A type of plastic", "A computer program", "A part of a robot"], correct_answer: "The brain's ability to change", explanation: "This is the brain's ability to create new neural connections during the learning process." }
		]
	},
    {
		section: "Section 3: COMPUTER VISION AND SPEECH",
		questions: [
			{ id: 31, question: "What is Computer Vision?", options: ["Computer vision", "Hearing", "Movement", "Memory"], correct_answer: "Computer vision", explanation: "This is a field of AI that enables computers to understand and analyze images and videos." },
			{ id: 32, question: "What is a pixel?", options: ["The smallest point on an image", "Processor name", "Keyboard type", "Part of a mouse"], correct_answer: "The smallest point on an image", explanation: "All digital images consist of millions of tiny dots called pixels." },
			{ id: 33, question: "What numbers express a pixel's color (in RGB)?", options: ["0-255", "0-100", "1-10", "10-20"], correct_answer: "0-255", explanation: "In the RGB model, each color (Red, Green, Blue) is represented by a number from 0 to 255." },
			{ id: 34, question: "What does the abbreviation NLP stand for?", options: ["Natural Language Processing", "New Light Power", "Net Line Post", "Next Level Plan"], correct_answer: "Natural Language Processing", explanation: "It is natural language processing, which allows computers to communicate in human language." },
			{ id: 35, question: "Which field does Face Recognition belong to?", options: ["Computer Vision", "NLP", "Robotics", "Hardware"], correct_answer: "Computer Vision", explanation: "This technology is built upon computer vision algorithms." },
			{ id: 36, question: "What is a chatbot?", options: ["A program for dialogue", "A virus", "A monitor", "A wire"], correct_answer: "A program for dialogue", explanation: "A chatbot is a program that conducts a dialogue with a person using AI and NLP." },
			{ id: 37, question: "What is a Deepfake?", options: ["AI-generated video", "A new game", "A phone model", "An ordinary message"], correct_answer: "AI-generated video", explanation: "Deepfake is a technology that uses AI to replace faces in videos with other faces." },
			{ id: 38, question: "What is OCR used for?", options: ["Converting image to text", "Listening to music", "A game", "Printing"], correct_answer: "Converting image to text", explanation: "OCR (Optical Character Recognition) is used to read and convert paper documents and photos into digital text." },
			{ id: 39, question: "What technology do Siri and Alexa use?", options: ["NLP and speech", "Images only", "Text only", "Nothing"], correct_answer: "NLP and speech", explanation: "These intelligent voice assistants use AI to understand and execute voice commands." },
			{ id: 40, question: "What is Google Translate based on?", options: ["Neural networks", "Simple dictionary", "Manual input", "Radio"], correct_answer: "Neural networks", explanation: "Google Translate uses complex neural models for accurate text translation." },
			{ id: 41, question: "How does a self-driving car 'see' the road?", options: ["Using cameras and LiDAR", "Human eye", "Using paper maps", "By sound"], correct_answer: "Using cameras and LiDAR", explanation: "Autopilots scan their surroundings using cameras and LiDAR sensors, analyzing data via AI." },
			{ id: 42, question: "What is LiDAR?", options: ["Laser measurement sensor", "Screen type", "Engine part", "Radio"], correct_answer: "Laser measurement sensor", explanation: "LiDAR measures the distance to objects using laser beams to create a 3D map." },
			{ id: 43, question: "What is image segmentation?", options: ["Dividing parts of a drawing", "Deleting a drawing", "Painting", "Printing"], correct_answer: "Dividing parts of a drawing", explanation: "This is the process of partitioning an image into separate parts (e.g., separating a tree from the sky)." },
			{ id: 44, question: "What is sentiment analysis?", options: ["Identifying text emotion", "Word counting", "Translation", "Printing"], correct_answer: "Identifying text emotion", explanation: "This technology determines whether a written text or review is positive, negative, or neutral." },
			{ id: 45, question: "How does computer vision help in medicine?", options: ["Analyzing X-rays and CT scans", "Equipment repair", "Hospital cleaning", "Patient lists"], correct_answer: "Analyzing X-rays and CT scans", explanation: "AI can detect diseases (such as cancer) on medical images at early stages with high accuracy." }
		]
	},
    {
		section: "Section 4: SCIENCE AND EDUCATION",
		questions: [
			{ id: 46, question: "What does fundamental science study?", options: ["Laws of nature", "Technology", "History", "Art"], correct_answer: "Laws of nature", explanation: "This science explores the foundations of the universe and the natural laws of the Cosmos." },
			{ id: 47, question: "Is mathematics important for AI?", options: ["Yes, very much", "No", "Only addition and subtraction", "Slightly"], correct_answer: "Yes, very much", explanation: "AI is entirely based on mathematics, especially statistics and linear algebra." },
			{ id: 48, question: "What is 'Bias' in AI?", options: ["Data error", "Speed", "Power", "Light"], correct_answer: "Data error", explanation: "If training data contains errors or stereotypes, AI can make unfair decisions." },
			{ id: 49, question: "What does AI ethics study?", options: ["Proper use of AI", "Speed of electricity", "Computer price", "Robot mechanics"], correct_answer: "Proper use of AI", explanation: "This field regulates moral issues of AI usage, such as safety and human rights." },
			{ id: 50, question: "What is technological singularity?", options: ["Point of AI superiority", "Shutdown", "Beginning", "Error"], correct_answer: "Point of AI superiority", explanation: "This is a hypothetical moment in the future when AI completely surpasses human intelligence." },
			{ id: 51, question: "Does a computer see color as a number?", options: ["True", "False"], correct_answer: "True", explanation: "All colors in a computer are represented by numbers (e.g., RGB: 255, 0, 0 for red)." },
			{ id: 52, question: "Can AI create music?", options: ["Yes", "No"], correct_answer: "Yes", explanation: "AI can generate new original music by analyzing thousands of existing melodies." },
			{ id: 53, question: "Which numbers are called binary?", options: ["0 and 1", "1 and 2", "0-9", "A-F"], correct_answer: "0 and 1", explanation: "Computers only understand the language of the digits 0 and 1." },
			{ id: 54, question: "Can AI diagnose diseases?", options: ["Yes", "No"], correct_answer: "Yes", explanation: "AI is a powerful assistant to doctors in analyzing medical data and diagnosing illnesses." },
			{ id: 55, question: "What is an algorithm?", options: ["Sequence of actions", "Monitor", "Memory", "Wire"], correct_answer: "Sequence of actions", explanation: "An algorithm is a step-by-step instruction for performing a specific task." },
			{ id: 56, question: "Do all robots have AI?", options: ["No", "Yes"], correct_answer: "No", explanation: "Some robots perform only simple pre-programmed actions and do not possess AI." },
			{ id: 57, question: "What role do quantum computers play in AI?", options: ["Incredibly high speed", "Only for games", "No role", "Shutdown"], correct_answer: "Incredibly high speed", explanation: "Quantum computers can perform complex AI calculations millions of times faster than ordinary ones." },
			{ id: 58, question: "Can AI write poetry?", options: ["Yes", "No"], correct_answer: "Yes", explanation: "Large Language Models (LLM) can write poetry and creative texts in various styles." },
			{ id: 59, question: "Is the Internet important for AI?", options: ["Yes, for data", "No", "Only for news", "Slightly"], correct_answer: "Yes, for data", explanation: "The Internet is the primary source of data for training most modern AI models." },
			{ id: 60, question: "Can AI take over jobs?", options: ["Yes, some", "No", "Only in the kitchen", "Never"], correct_answer: "Yes, some", explanation: "AI replaces routine and automated tasks, but simultaneously creates many new professions." },
			{ id: 61, question: "Who is Sophia?", options: ["A humanoid robot", "A car", "A phone", "A book"], correct_answer: "A humanoid robot", explanation: "Sophia is the first robot to receive citizenship of a state (Saudi Arabia)." },
			{ id: 62, question: "Can AI predict the weather?", options: ["Yes", "No"], correct_answer: "Yes", explanation: "AI analyzes climate data and predicts the weather with high accuracy." },
			{ id: 63, question: "What is the Turing Award?", options: ["Nobel Prize in IT", "Oscar", "Sports award", "Medal"], correct_answer: "Nobel Prize in IT", explanation: "This is the most prestigious award in the field of computer science." },
			{ id: 64, question: "Can AI independently correct itself?", options: ["Yes, in some cases", "No", "Only at night", "Only with water"], correct_answer: "Yes, in some cases", explanation: "Some advanced algorithms can adjust their parameters to improve the result." },
			{ id: 65, question: "Can robots pick up an egg without breaking it?", options: ["True", "False"], correct_answer: "True", explanation: "Thanks to sensitive sensors and complex algorithms, robots can work with very fragile objects." }
		]
	},
	{
		section: "Section 5: AI ETHICS AND SAFETY",
		questions: [
			{ id: 66, question: "What causes the problem of bias in Artificial Intelligence?", options: ["A technical error in the processor", "Missing parameters in the training data", "The fact that robots dislike humans"], correct_answer: "Missing parameters in the training data", explanation: "Bias occurs when the training data is incomplete or only covers a limited group of people." },
			{ id: 67, question: "What is a Deepfake?", options: ["A new type of computer game", "Fake photo, video, and audio editing using AI", "An anti-virus protection system"], correct_answer: "Fake photo, video, and audio editing using AI", explanation: "Deepfake is a technology that uses neural networks to realistically replace people's faces and voices in videos." },
			{ id: 68, question: "What does physical safety in AI involve?", options: ["Preventing harm to people and their property by robots", "Using complex passwords", "Protecting email from hackers"], correct_answer: "Preventing harm to people and their property by robots", explanation: "This principle ensures that AI-powered devices (such as drones or robots) do not cause harm to human health." },
			{ id: 69, question: "Why did a robot teacher give a student a low grade for homework?", options: ["Because the answers were incorrect", "Because it 'disliked' the student's handwriting and linked it to a poor answer", "Because the student submitted the assignment late"], correct_answer: "Because it 'disliked' the student's handwriting and linked it to a poor answer", explanation: "This is an example of an algorithmic error finding a false correlation in the data." },
			{ id: 70, question: "What does the concept of 'AI Ethics' study?", options: ["How to write programming code correctly", "Questions of 'good and evil', fairness, and safety of AI systems", "Methods for speeding up processors"], correct_answer: "Questions of 'good and evil', fairness, and safety of AI systems", explanation: "AI ethics is a set of rules for creating technologies that benefit humanity and do no harm." },
			{ id: 71, question: "Which action during AI training leads to a 'personal information leak'?", options: ["When AI is trained only on cat photos", "When users' personal data is used without proper protection", "When AI answers technical questions"], correct_answer: "When users' personal data is used without proper protection", explanation: "Privacy protection requires that people's personal data is not disclosed when training AI models." },
			{ id: 72, question: "What happens if a facial recognition system is trained only on photos of people with fair skin?", options: ["The system will work better", "Bias will occur, and the system will not recognize people with dark skin", "The system will automatically find new photos"], correct_answer: "Bias will occur, and the system will not recognize people with dark skin", explanation: "This is a fairness issue in AI; the model must be trained on diverse data." },
			{ id: 73, question: "When is the use of 'Deepfake' acceptable?", options: ["To steal money from people", "To spread fake news", "Only for entertainment and harmless jokes"], correct_answer: "Only for entertainment and harmless jokes", explanation: "Deepfakes should only be used for creative or entertainment purposes with prior notification to the viewer." },
			{ id: 74, question: "Can AI become a complete replacement for human intellectual abilities in studies?", options: ["Yes, there is no need to study anymore", "No, AI is only a learning assistant", "Only if there is no internet"], correct_answer: "No, AI is only a learning assistant", explanation: "AI cannot fully replace critical thinking and human creativity." },
			{ id: 75, question: "Why is 'Computer Vision' technology used in driver cabins?", options: ["To count passengers", "To detect drowsiness and prevent accidents", "To play music"], correct_answer: "To detect drowsiness and prevent accidents", explanation: "This is an example of the ethical use of AI to save human lives." },
			{ id: 76, question: "Why does AI refrain from making an accurate medical diagnosis or prescribing medicine?", options: ["Because it has no data on medicine", "Because only a qualified doctor can diagnose and be responsible", "Because medicine is too expensive"], correct_answer: "Because only a qualified doctor can diagnose and be responsible", explanation: "Legal and ethical responsibility in medicine lies with the human (doctor), not the program." },
			{ id: 77, question: "What do developers do if a user insists on receiving answers to unethical questions?", options: ["They give them a reward", "They blacklist the user or restrict access", "They order the AI to give a false answer"], correct_answer: "They blacklist the user or restrict access", explanation: "Companies set up safety filters to prevent AI from being used for malicious purposes." },
			{ id: 78, question: "What is the main danger of a 'Deepfake' for an individual?", options: ["It simply wastes people's time", "It can lead to discredit and job loss", "It reduces video quality"], correct_answer: "It can lead to discredit and job loss", explanation: "Deepfakes can be used to create slander and spread false information about a person." },
			{ id: 79, question: "What plan have engineers provided for cases of autopilot 'uncertainty'?", options: ["The car must increase speed", "The car either stops or asks the human to take control", "The car must turn in any direction"], correct_answer: "The car either stops or asks the human to take control", explanation: "This is the Safety First principle, which returns control to the human when an error occurs." },
			{ id: 80, question: "How does the 'Information Bubble' affect entertainment systems?", options: ["It provides more information", "It limits the horizon by showing only what we like", "It speeds up the internet"], correct_answer: "It limits the horizon by showing only what we like", explanation: "Recommendation algorithms trap us within our own preferences, which hinders the development of a broader worldview." },
			{ id: 81, question: "Which principle requires that AI decision-making processes be understandable?", options: ["Honesty", "Responsibility", "Transparency"], correct_answer: "Transparency", explanation: "Transparency means we should understand why the AI made a specific decision (Explainable AI)." },
			{ id: 82, question: "What is the advantage of using AI when learning to program?", options: ["Creating a personal learning program based on existing knowledge", "AI writes the code instead of the student", "AI automatically gives an 'excellent' grade"], correct_answer: "Creating a personal learning program based on existing knowledge", explanation: "AI can offer each student suitable material depending on their learning pace." },
			{ id: 83, question: "What risk can the use of AI in grocery ordering carry?", options: ["Goods will become very expensive", "If AI makes a mistake, a huge amount of food could be spoiled and thrown away", "Stores will close completely"], correct_answer: "If AI makes a mistake, a huge amount of food could be spoiled and thrown away", explanation: "An algorithmic error in inventory management can lead to major economic and environmental losses." },
			{ id: 84, question: "How does joining the 'Declaration of Ethics in AI' happen?", options: ["It is mandatory", "It is voluntary", "Only with special permission"], correct_answer: "It is voluntary", explanation: "Most AI ethical codes in the world are adopted as voluntary recommendations for technology companies." },
			{ id: 85, question: "What should developers do with AI-generated content?", options: ["Hide it", "Label it", "Delete it"], correct_answer: "Label it", explanation: "To prevent people from being misled, it should be indicated that the text or image was created by AI." },
			{ id: 86, question: "Who is responsible for the distribution of illegal information created by AI?", options: ["Only the AI robot", "The user who distributed the information", "No one is responsible"], correct_answer: "The user who distributed the information", explanation: "From a legal standpoint, the user is responsible for the use and distribution of AI results." },
			{ id: 87, question: "Which action is recommended for a responsible user?", options: ["Using AI to pass exams", "Reporting to the developer if the AI creates incorrect information", "Hiding the use of AI in professional activities"], correct_answer: "Reporting to the developer if the AI creates incorrect information", explanation: "This helps improve models and prevent errors in the future." },
			{ id: 88, question: "What does the phrase 'AI is always just one of the tools in your hands' mean?", options: ["AI should replace people", "A human should maintain control and make final decisions", "The technology is perfect"], correct_answer: "A human should maintain control and make final decisions", explanation: "AI should serve as an assistant, but responsibility for vital decisions must remain with the human." }
		]
	},
	{
		section: "Section 6: ECOLOGY AND SPACE",
		questions: [
			{ id: 89, question: "For which of the following ecological purposes is AI used in Tajikistan?", options: ["To increase the amount of precipitation", "To track the rate of glacier melting and the appearance of cracks", "To replace all forestry workers"], correct_answer: "To track the rate of glacier melting and the appearance of cracks", explanation: "In Tajikistan, AI is used to monitor the condition of glaciers and predict their melting, which is critical for the region's water resources." },
			{ id: 90, question: "With what accuracy can AI predict the consequences of climate change based on machine learning models?", options: ["Up to 50%", "Up to 75%", "Up to 90%"], correct_answer: "Up to 90%", explanation: "Modern AI models, by analyzing vast amounts of meteorological data, can predict climate changes with very high accuracy." },
			{ id: 91, question: "Why is Tajikistan more vulnerable to natural disasters such as mudflows and avalanches?", options: ["Because there are many rivers in the country", "Because 93% of the country's territory is occupied by mountains", "Because AI does not work in the mountains"], correct_answer: "Because 93% of the country's territory is occupied by mountains", explanation: "Mountainous terrain increases natural risks, and using AI for early warning of mudflows and avalanches in these regions is vital." },
			{ id: 92, question: "How can a neural network recognize each snow leopard individually?", options: ["By the weight of the animal", "By the unique pattern of spots on its fur (pelt)", "By the sound it makes"], correct_answer: "By the unique pattern of spots on its fur (pelt)", explanation: "The patterns on a snow leopard's pelt are unique, like human fingerprints. AI analyzes these patterns to distinguish animals from one another." },
			{ id: 93, question: "Approximately how many photographs was the AI trained on to recognize 10 animal species?", options: ["1,000 photographs", "10,000 photographs", "40,000 photographs"], correct_answer: "40,000 photographs", explanation: "To accurately recognize objects in nature, neural networks require a massive amount of visual data (photographs)." },
			{ id: 94, question: "What does the term 'Digital Shield' mean in ecology?", options: ["Building iron walls around the forest", "Using AI technologies for environmental protection and monitoring", "Banning the use of the Internet in nature"], correct_answer: "Using AI technologies for environmental protection and monitoring", explanation: "A Digital Shield is a complex of sensors and algorithms used to prevent deforestation and illegal hunting." },
			{ id: 95, question: "What is the concept of a 'Digital Twin' used for?", options: ["For video games in space", "To create a virtual copy of the planet and human for risk analysis", "To double the amount of food"], correct_answer: "To create a virtual copy of the planet and human for risk analysis", explanation: "A Digital Twin is a computer model of reality that allows testing various hazardous scenarios without harming the real world." },
			{ id: 96, question: "Who performs the work of preparing a base before humans land on a new planet?", options: ["The colonists themselves", "Autonomous robots under human guidance", "Local animals of the planet"], correct_answer: "Autonomous robots under human guidance", explanation: "AI-powered robots can work in conditions dangerous for humans, preparing the primary infrastructure in space." },
			{ id: 97, question: "What is the role of sensors in a space mission?", options: ["Only for taking beautiful landscapes", "For recording seismic activity, climate, and health indicators in real-time", "For destroying local insects"], correct_answer: "For recording seismic activity, climate, and health indicators in real-time", explanation: "Sensors are the 'eyes and ears' of AI in space, recording any environmental changes in seconds." },
			{ id: 98, question: "What factors does Artificial Intelligence consider when choosing a landing site?", options: ["Only the presence of iron deposits", "Only the beauty of the landscape", "A complex of factors: water, energy, protection from cataclysms, and biological safety"], correct_answer: "A complex of factors: water, energy, protection from cataclysms, and biological safety", explanation: "AI can analyze thousands of maps and data points to find the optimal and safest landing spot for spacecraft." }
		]
	},
	{
		section: "Section 7: HEALTHCARE",
		questions: [
			{ id: 99, question: "What does the concept of a 'Second Opinion' mean when using AI in medicine?", options: ["When a doctor consults with another patient", "When AI offers its own diagnosis to verify a doctor's decision", "When a doctor prescribes the same medicine to two patients"], correct_answer: "When AI offers its own diagnosis to verify a doctor's decision", explanation: "AI acts as a doctor's assistant, offering an alternative diagnosis to reduce the risk of human error." },
			{ id: 100, question: "By what percentage can AI increase the probability of correct diagnosis for kidney diseases?", options: ["Up to 50%", "Up to 75%", "Up to 94%"], correct_answer: "Up to 94%", explanation: "Thanks to precise analysis of biological markers, AI can detect kidney diseases at early stages with high accuracy." },
			{ id: 101, question: "How does 'Computer Vision' help in examining X-rays?", options: ["It turns X-rays into videos", "It highlights suspicious areas in color and provides a description within minutes", "It improves the quality of the X-ray machine itself"], correct_answer: "It highlights suspicious areas in color and provides a description within minutes", explanation: "Algorithms compare thousands of images in seconds, finding even the smallest changes or tumors." },
			{ id: 102, question: "How can AI detect respiratory diseases?", options: ["Through analysis of audio recordings of breathing and speech", "By measuring the patient's weight", "By checking the patient's running speed"], correct_answer: "Through analysis of audio recordings of breathing and speech", explanation: "AI can recognize subtle changes in voice and breathing patterns that are signs of respiratory illnesses." },
			{ id: 103, question: "What is the advantage of a 'Digital Patient Profile'?", options: ["It is only needed to calculate treatment costs", "It allows comparing the entire medical history to predict dangerous trends", "It allows the patient to treat themselves without a doctor"], correct_answer: "It allows comparing the entire medical history to predict dangerous trends", explanation: "This is a database covering a patient's entire life, allowing the doctor to see the full picture of their health." },
			{ id: 104, question: "Can AI completely replace a doctor?", options: ["Yes, AI never makes mistakes", "No, AI performs only routine tasks; the final decision and diagnosis are made by the doctor", "Only if there is high-speed internet"], correct_answer: "No, AI performs only routine tasks; the final decision and diagnosis are made by the doctor", explanation: "AI is just a powerful tool, but intuition and ethical responsibility for the diagnosis belong only to the human." },
			{ id: 105, question: "What is the main benefit of a digital patient profile when prescribing treatment?", options: ["It allows finding cheaper medicines", "AI can account for allergies and drug intolerances based on years of history", "It allows the patient to be treated without a doctor's involvement"], correct_answer: "AI can account for allergies and drug intolerances based on years of history", explanation: "This ensures patient safety by preventing side effects from incompatible medications." },
			{ id: 106, question: "How does artificial intelligence help hearing-impaired people?", options: ["It heals their ears", "It converts other people's speech into text in real-time so they can read it", "It teaches them sign language"], correct_answer: "It converts other people's speech into text in real-time so they can read it", explanation: "Speech-to-Text technologies help people with disabilities communicate without barriers." },
			{ id: 107, question: "How do modern prosthetics for people who have lost limbs work?", options: ["They move using ordinary batteries", "They receive brain signals and adapt to body functions using AI", "They must be controlled by another person"], correct_answer: "They receive brain signals and adapt to body functions using AI", explanation: "Bionic prosthetics using AI analyze nerve signals and replicate natural human movements." },
			{ id: 108, question: "Why is self-treatment using AI chatbots strictly prohibited?", options: ["Because chatbots cost money", "Because a chatbot cannot perform a medical examination and there is a high risk of error", "Because chatbots only answer in English"], correct_answer: "Because a chatbot cannot perform a medical examination and there is a high risk of error", explanation: "AI can 'hallucinate' and provide incorrect information. It is always necessary to consult a living specialist." },
			{ id: 109, question: "How can AI notice the start of an epidemic before hospitals do?", options: ["It calls people's homes", "It analyzes the growth of internet search queries about disease symptoms", "It measures the air temperature"], correct_answer: "It analyzes the growth of internet search queries about disease symptoms", explanation: "By analyzing Big Data (queries in Google and social networks), AI can predict a disease outbreak." }
	]
	},
	{
		section: "Section 8: INDUSTRY AND TECHNOLOGY",
		questions: [
			{ id: 110, question: "How do self-driving taxis operate in the city of Innopolis since 2023?", options: ["Still with a physical driver inside the car", "With a remote control and without a test driver inside the car", "Only inside special buildings"], correct_answer: "With a remote control and without a test driver inside the car", explanation: "This is a high level of automation where the vehicle is fully autonomous." },
			{ id: 111, question: "How does the development of AI technologies affect the consumer computer market?", options: ["Makes computers more expensive and slower", "Supercomputer technologies are entering the consumer market", "It has no effect"], correct_answer: "Supercomputer technologies are entering the consumer market", explanation: "Massive computing power is now becoming accessible to ordinary users." },
			{ id: 112, question: "What advantage does the use of AI provide in translation programs compared to old algorithms?", options: ["Translates only individual words", "Allows translating large fragments of text with high quality", "Always performs translation with a robotic voice"], correct_answer: "Allows translating large fragments of text with high quality", explanation: "Neural models understand the context of a sentence rather than just translating individual words." },
			{ id: 113, question: "To whom does the AI send a group of 'questionable quality' goods during production control?", options: ["To the trash bin", "To a human for final evaluation", "To another market"], correct_answer: "To a human for final evaluation", explanation: "AI filters out suspicious objects, but the final decision is made by a human." },
			{ id: 114, question: "How does AI help industry in situational forecasting?", options: ["To increase working hours", "To eliminate human factor errors (fatigue, negligence)", "To replace natural products"], correct_answer: "To eliminate human factor errors (fatigue, negligence)", explanation: "Algorithms do not get tired and do not lose focus." },
			{ id: 115, question: "What is the main task of 'rovers' (delivery robots)?", options: ["For transporting people", "For delivering food and mail to the desired address", "For cleaning streets"], correct_answer: "For delivering food and mail to the desired address", explanation: "Rovers are small autonomous robots designed for transporting small loads over short distances." }
		]
	},
    {
		section: "Section 9: CREATIVITY AND PROJECTS",
		questions: [
			{ id: 116, question: "How does a 'generative adversarial' model (GAN) work when creating images?", options: ["One algorithm simply colors a drawing", "Two algorithms compete: one creates an idea and the other checks it", "The algorithm steals people's drawings from the internet"], correct_answer: "Two algorithms compete: one creates an idea and the other checks it", explanation: "A GAN (Generative Adversarial Network) consists of two networks: the Generator creates an image, and the Discriminator tries to find errors in it so the result looks realistic." },
			{ id: 117, question: "What is a 'Prompt' in the process of working with AI?", options: ["The name of a type of powerful computer", "A text description a person gives to AI to get the desired result", "A robot's power-off button"], correct_answer: "A text description a person gives to AI to get the desired result", explanation: "Prompt engineering is the art of correctly setting tasks for AI so that it generates accurate and high-quality responses." },
			{ id: 118, question: "Approximately how many examples are needed to train an AI so it can draw a high-quality image of a human?", options: ["A few hundred images", "Millions of photos and drawings", "Only 10 photos"], correct_answer: "Millions of photos and drawings", explanation: "To understand anatomy and the details of a human face, AI must process a massive database (dataset)." },
			{ id: 119, question: "From the union of which fields did the science of 'Bioinformatics' emerge?", options: ["Mathematics and History", "Biology and Computer Science", "Chemistry and Physical Education"], correct_answer: "Biology and Computer Science", explanation: "Bioinformatics uses computer algorithms to analyze complex genetic and biological data." },
			{ id: 120, question: "What is the main task of a 'Technologist' in a school project?", options: ["Organizing the team's work", "Working with AI systems to generate materials", "Presenting results"], correct_answer: "Working with AI systems to generate materials", explanation: "The technologist in a team is responsible for using AI tools (such as ChatGPT or Midjourney) to develop the project." }
		]
	}
]

async function run() {
    try {
        await Quiz.deleteMany({}); // THIS LINE DELETES OLD QUESTIONS
        await Quiz.insertMany(data);
        console.log("-----------------------------------------");
        console.log("✅ DATABASE FULLY POPULATED (WITH 9 SECTIONS AND EXPLANATIONS!)");
        
        const countRes = await Quiz.aggregate([{$project: {count: {$size: "$questions"}}}]);
        const total = countRes.reduce((a, b) => a + b.count, 0);
        
        console.log(`📊 Total number of questions: ${total}`);
        console.log("🚀 Now run 'node server.js'.");
        console.log("-----------------------------------------");
        process.exit();
    } catch (err) {
        console.error("❌ Import error:", err);
        process.exit(1);
    }
}

run();

